# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "oliverklee"
    reviewers:
      - "oliverklee"
    open-pull-requests-limit: 10

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    assignees:
      - "oliverklee"
    reviewers:
      - "oliverklee"
    open-pull-requests-limit: 10
